### ISSUE TITLE
Hey thank you

### ISSUE THREAD

**Issue by xentzenith** [nalyvka/nalyvka#1]
Hey thank you for following me, I followed you back can you just give star last 2 repository which is

https://github.com/xentzenith/x3nos

https://github.com/xentzenith/weather-final-project

I will yours too. Just drop link after starring.

**Comment by nalyvka** [comment]
It's the other way around: you followed me first, and I added you back

But sure, I don't mind:

https://github.com/nalyvka/pythonBasics

https://github.com/nalyvka/landingPage

And please don't **spam**, tagging random people; I understand that you want follows/stars, but focus on your work: that's more important than popularity.
